website:
  url: "https://mreider.com"
  name: "MR"
  basePath: "/"
  devPath: "/"

menu:
  - title: "Home"
    path: "index.md"
  - title: "Tech"
    path: "tech/index.md"
  - title: "Life"
    path: "life/index.md"
  - title: "Projects"
    path: "projects/index.md"
  - title: "Dad"
    path: "family/pete.md"
  - title: "Family"
    path: "family/index.md"
