baseURL = 'https://mreider.com/'
languageCode = 'en-us'
title = 'MR'

[params]
  description = "Matthew Reider's personal website"
  author = "Matt Reider"

[taxonomies]
  author = 'authors'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 2
  [[menu.main]]
    name = "Life"
    url = "/life/"
    weight = 3
  [[menu.main]]
    name = "Tech"
    url = "/tech/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Deutsch"
    url = "/deutsch/"
    weight = 6
